import { Option } from "./Types";

export const countries: Option[] = [
  { name_en: "Afghanistan", name_ar: "أفغانستان", code: "AF" },
  { name_en: "Albania", name_ar: "ألبانيا", code: "AL" },
  { name_en: "Algeria", name_ar: "الجزائر", code: "DZ" },
  { name_en: "Andorra", name_ar: "أندورا", code: "AD" },
  { name_en: "Angola", name_ar: "أنغولا", code: "AO" },
  { name_en: "Argentina", name_ar: "الأرجنتين", code: "AR" },
  { name_en: "Armenia", name_ar: "أرمينيا", code: "AM" },
  { name_en: "Australia", name_ar: "أستراليا", code: "AU" },
  { name_en: "Austria", name_ar: "النمسا", code: "AT" },
  { name_en: "Azerbaijan", name_ar: "أذربيجان", code: "AZ" },
  { name_en: "Bahrain", name_ar: "البحرين", code: "BH" },
  { name_en: "Bangladesh", name_ar: "بنغلاديش", code: "BD" },
  { name_en: "Belgium", name_ar: "بلجيكا", code: "BE" },
  { name_en: "Brazil", name_ar: "البرازيل", code: "BR" },
  { name_en: "Canada", name_ar: "كندا", code: "CA" },
  { name_en: "China", name_ar: "الصين", code: "CN" },
  { name_en: "Denmark", name_ar: "الدنمارك", code: "DK" },
  { name_en: "Egypt", name_ar: "مصر", code: "EG" },
  { name_en: "Finland", name_ar: "فنلندا", code: "FI" },
  { name_en: "France", name_ar: "فرنسا", code: "FR" },
  { name_en: "Germany", name_ar: "ألمانيا", code: "DE" },
  { name_en: "India", name_ar: "الهند", code: "IN" },
  { name_en: "Indonesia", name_ar: "إندونيسيا", code: "ID" },
  { name_en: "Iran", name_ar: "إيران", code: "IR" },
  { name_en: "Iraq", name_ar: "العراق", code: "IQ" },
  { name_en: "Ireland", name_ar: "أيرلندا", code: "IE" },
  { name_en: "Italy", name_ar: "إيطاليا", code: "IT" },
  { name_en: "Japan", name_ar: "اليابان", code: "JP" },
  { name_en: "Jordan", name_ar: "الأردن", code: "JO" },
  { name_en: "Kuwait", name_ar: "الكويت", code: "KW" },
  { name_en: "Lebanon", name_ar: "لبنان", code: "LB" },
  { name_en: "Libya", name_ar: "ليبيا", code: "LY" },
  { name_en: "Malaysia", name_ar: "ماليزيا", code: "MY" },
  { name_en: "Mexico", name_ar: "المكسيك", code: "MX" },
  { name_en: "Morocco", name_ar: "المغرب", code: "MA" },
  { name_en: "Netherlands", name_ar: "هولندا", code: "NL" },
  { name_en: "New Zealand", name_ar: "نيوزيلندا", code: "NZ" },
  { name_en: "Nigeria", name_ar: "نيجيريا", code: "NG" },
  { name_en: "Norway", name_ar: "النرويج", code: "NO" },
  { name_en: "Oman", name_ar: "عمان", code: "OM" },
  { name_en: "Pakistan", name_ar: "باكستان", code: "PK" },
  { name_en: "Palestine", name_ar: "فلسطين", code: "PS" },
  { name_en: "Philippines", name_ar: "الفلبين", code: "PH" },
  { name_en: "Poland", name_ar: "بولندا", code: "PL" },
  { name_en: "Portugal", name_ar: "البرتغال", code: "PT" },
  { name_en: "Qatar", name_ar: "قطر", code: "QA" },
  { name_en: "Romania", name_ar: "رومانيا", code: "RO" },
  { name_en: "Russia", name_ar: "روسيا", code: "RU" },
  { name_en: "Saudi Arabia", name_ar: "السعودية", code: "SA" },
  { name_en: "South Africa", name_ar: "جنوب أفريقيا", code: "ZA" },
  { name_en: "South Korea", name_ar: "كوريا الجنوبية", code: "KR" },
  { name_en: "Spain", name_ar: "إسبانيا", code: "ES" },
  { name_en: "Sudan", name_ar: "السودان", code: "SD" },
  { name_en: "Sweden", name_ar: "السويد", code: "SE" },
  { name_en: "Switzerland", name_ar: "سويسرا", code: "CH" },
  { name_en: "Syria", name_ar: "سوريا", code: "SY" },
  { name_en: "Thailand", name_ar: "تايلاند", code: "TH" },
  { name_en: "Tunisia", name_ar: "تونس", code: "TN" },
  { name_en: "Turkey", name_ar: "تركيا", code: "TR" },
  { name_en: "Ukraine", name_ar: "أوكرانيا", code: "UA" },
  {
    name_en: "United Arab Emirates",
    name_ar: "الإمارات العربية المتحدة",
    code: "AE",
  },
  { name_en: "United Kingdom", name_ar: "المملكة المتحدة", code: "GB" },
  { name_en: "United States", name_ar: "الولايات المتحدة", code: "US" },
  { name_en: "Venezuela", name_ar: "فنزويلا", code: "VE" },
  { name_en: "Vietnam", name_ar: "فيتنام", code: "VN" },
  { name_en: "Yemen", name_ar: "اليمن", code: "YE" },
];
